### ISSUE TITLE
Publish this please

### ISSUE THREAD

**Issue by Firescar96** [iswdp/termplot#2]
would you mind publishing this on pypi?

**Comment by seanturner026** [comment]
Yeah I would like this to happen as well

**Comment by iswdp** [comment]
I've never published on pypi before but I'll give it a try.

**Comment by Firescar96** [comment]
It's pretty painless:
Here's a guide https://jonemo.github.io/neubertify/2017/09/13/publishing-your-first-pypi-package/

**Comment by iswdp** [comment]
the guide is incomplete.  never tells you how to build the tar.  i think this has something to do with setuptools maybe?

**Comment by Firescar96** [comment]
When I did it a couple weeks ago I used http://peterdowns.com/posts/first-time-with-pypi.html but it doesn't work exactly as described anymore. Pypi migrated to a new server and something about this method is unnecessary now, but most of it is accurate. Give it a shot?

**Comment by iswdp** [comment]
Going through a setuptools tutorial at the moment.  I've put off learning this stuff for way too long.  Also need to learn git as well as I know literally nothing about working with other developers.

**Comment by iswdp** [comment]
Its done.
